package com.waxjx.largescale.dao;

import com.waxjx.largescale.model.Curriculumplans;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CurriculumplansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String curriculumplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    int insert(Curriculumplans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    int insertSelective(Curriculumplans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    Curriculumplans selectByPrimaryKey(String curriculumplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Curriculumplans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curriculumplans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Curriculumplans record);
}