package com.waxjx.largescale.dao;

import com.waxjx.largescale.model.Grades;
import com.waxjx.largescale.model.GradesKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface GradesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GradesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    int insert(Grades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    int insertSelective(Grades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    Grades selectByPrimaryKey(GradesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Grades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Grades record);
}