package com.waxjx.largescale.dao;

import com.waxjx.largescale.model.Teachers;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TeachersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    int insert(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    int insertSelective(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    Teachers selectByPrimaryKey(String teacherid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Teachers record);
}