package com.waxjx.largescale.model;

public class Curriculumplans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.curriculumPlanId
     *
     * @mbg.generated
     */
    private String curriculumplanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.planName
     *
     * @mbg.generated
     */
    private String planname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.planDescription
     *
     * @mbg.generated
     */
    private String plandescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.creditRequirement
     *
     * @mbg.generated
     */
    private Double creditrequirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_one
     *
     * @mbg.generated
     */
    private Double coursecategoryOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_two
     *
     * @mbg.generated
     */
    private Double coursecategoryTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_three
     *
     * @mbg.generated
     */
    private Double coursecategoryThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_four
     *
     * @mbg.generated
     */
    private Double coursecategoryFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_five
     *
     * @mbg.generated
     */
    private Double coursecategoryFive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_six
     *
     * @mbg.generated
     */
    private Double coursecategorySix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curriculumplans.courseCategory_seven
     *
     * @mbg.generated
     */
    private Double coursecategorySeven;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.curriculumPlanId
     *
     * @return the value of curriculumplans.curriculumPlanId
     *
     * @mbg.generated
     */
    public String getCurriculumplanid() {
        return curriculumplanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.curriculumPlanId
     *
     * @param curriculumplanid the value for curriculumplans.curriculumPlanId
     *
     * @mbg.generated
     */
    public void setCurriculumplanid(String curriculumplanid) {
        this.curriculumplanid = curriculumplanid == null ? null : curriculumplanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.major
     *
     * @return the value of curriculumplans.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.major
     *
     * @param major the value for curriculumplans.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.planName
     *
     * @return the value of curriculumplans.planName
     *
     * @mbg.generated
     */
    public String getPlanname() {
        return planname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.planName
     *
     * @param planname the value for curriculumplans.planName
     *
     * @mbg.generated
     */
    public void setPlanname(String planname) {
        this.planname = planname == null ? null : planname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.planDescription
     *
     * @return the value of curriculumplans.planDescription
     *
     * @mbg.generated
     */
    public String getPlandescription() {
        return plandescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.planDescription
     *
     * @param plandescription the value for curriculumplans.planDescription
     *
     * @mbg.generated
     */
    public void setPlandescription(String plandescription) {
        this.plandescription = plandescription == null ? null : plandescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.creditRequirement
     *
     * @return the value of curriculumplans.creditRequirement
     *
     * @mbg.generated
     */
    public Double getCreditrequirement() {
        return creditrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.creditRequirement
     *
     * @param creditrequirement the value for curriculumplans.creditRequirement
     *
     * @mbg.generated
     */
    public void setCreditrequirement(Double creditrequirement) {
        this.creditrequirement = creditrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.remarks
     *
     * @return the value of curriculumplans.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.remarks
     *
     * @param remarks the value for curriculumplans.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_one
     *
     * @return the value of curriculumplans.courseCategory_one
     *
     * @mbg.generated
     */
    public Double getCoursecategoryOne() {
        return coursecategoryOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_one
     *
     * @param coursecategoryOne the value for curriculumplans.courseCategory_one
     *
     * @mbg.generated
     */
    public void setCoursecategoryOne(Double coursecategoryOne) {
        this.coursecategoryOne = coursecategoryOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_two
     *
     * @return the value of curriculumplans.courseCategory_two
     *
     * @mbg.generated
     */
    public Double getCoursecategoryTwo() {
        return coursecategoryTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_two
     *
     * @param coursecategoryTwo the value for curriculumplans.courseCategory_two
     *
     * @mbg.generated
     */
    public void setCoursecategoryTwo(Double coursecategoryTwo) {
        this.coursecategoryTwo = coursecategoryTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_three
     *
     * @return the value of curriculumplans.courseCategory_three
     *
     * @mbg.generated
     */
    public Double getCoursecategoryThree() {
        return coursecategoryThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_three
     *
     * @param coursecategoryThree the value for curriculumplans.courseCategory_three
     *
     * @mbg.generated
     */
    public void setCoursecategoryThree(Double coursecategoryThree) {
        this.coursecategoryThree = coursecategoryThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_four
     *
     * @return the value of curriculumplans.courseCategory_four
     *
     * @mbg.generated
     */
    public Double getCoursecategoryFour() {
        return coursecategoryFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_four
     *
     * @param coursecategoryFour the value for curriculumplans.courseCategory_four
     *
     * @mbg.generated
     */
    public void setCoursecategoryFour(Double coursecategoryFour) {
        this.coursecategoryFour = coursecategoryFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_five
     *
     * @return the value of curriculumplans.courseCategory_five
     *
     * @mbg.generated
     */
    public Double getCoursecategoryFive() {
        return coursecategoryFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_five
     *
     * @param coursecategoryFive the value for curriculumplans.courseCategory_five
     *
     * @mbg.generated
     */
    public void setCoursecategoryFive(Double coursecategoryFive) {
        this.coursecategoryFive = coursecategoryFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_six
     *
     * @return the value of curriculumplans.courseCategory_six
     *
     * @mbg.generated
     */
    public Double getCoursecategorySix() {
        return coursecategorySix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_six
     *
     * @param coursecategorySix the value for curriculumplans.courseCategory_six
     *
     * @mbg.generated
     */
    public void setCoursecategorySix(Double coursecategorySix) {
        this.coursecategorySix = coursecategorySix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curriculumplans.courseCategory_seven
     *
     * @return the value of curriculumplans.courseCategory_seven
     *
     * @mbg.generated
     */
    public Double getCoursecategorySeven() {
        return coursecategorySeven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curriculumplans.courseCategory_seven
     *
     * @param coursecategorySeven the value for curriculumplans.courseCategory_seven
     *
     * @mbg.generated
     */
    public void setCoursecategorySeven(Double coursecategorySeven) {
        this.coursecategorySeven = coursecategorySeven;
    }
}