package com.waxjx.largescale.model;

public class GradesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.studentId
     *
     * @mbg.generated
     */
    private String studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.courseId
     *
     * @mbg.generated
     */
    private String courseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.gradeId
     *
     * @mbg.generated
     */
    private String gradeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.studentId
     *
     * @return the value of grades.studentId
     *
     * @mbg.generated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.studentId
     *
     * @param studentid the value for grades.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.courseId
     *
     * @return the value of grades.courseId
     *
     * @mbg.generated
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.courseId
     *
     * @param courseid the value for grades.courseId
     *
     * @mbg.generated
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid == null ? null : courseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.gradeId
     *
     * @return the value of grades.gradeId
     *
     * @mbg.generated
     */
    public String getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.gradeId
     *
     * @param gradeid the value for grades.gradeId
     *
     * @mbg.generated
     */
    public void setGradeid(String gradeid) {
        this.gradeid = gradeid == null ? null : gradeid.trim();
    }
}