package com.waxjx.largescale.model;

public class Grades extends GradesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.score
     *
     * @mbg.generated
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.enrollmentStatus
     *
     * @mbg.generated
     */
    private Short enrollmentstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.gpa
     *
     * @mbg.generated
     */
    private Double gpa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.assessmentMethod
     *
     * @mbg.generated
     */
    private String assessmentmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.score
     *
     * @return the value of grades.score
     *
     * @mbg.generated
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.score
     *
     * @param score the value for grades.score
     *
     * @mbg.generated
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.enrollmentStatus
     *
     * @return the value of grades.enrollmentStatus
     *
     * @mbg.generated
     */
    public Short getEnrollmentstatus() {
        return enrollmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.enrollmentStatus
     *
     * @param enrollmentstatus the value for grades.enrollmentStatus
     *
     * @mbg.generated
     */
    public void setEnrollmentstatus(Short enrollmentstatus) {
        this.enrollmentstatus = enrollmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.gpa
     *
     * @return the value of grades.gpa
     *
     * @mbg.generated
     */
    public Double getGpa() {
        return gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.gpa
     *
     * @param gpa the value for grades.gpa
     *
     * @mbg.generated
     */
    public void setGpa(Double gpa) {
        this.gpa = gpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.assessmentMethod
     *
     * @return the value of grades.assessmentMethod
     *
     * @mbg.generated
     */
    public String getAssessmentmethod() {
        return assessmentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.assessmentMethod
     *
     * @param assessmentmethod the value for grades.assessmentMethod
     *
     * @mbg.generated
     */
    public void setAssessmentmethod(String assessmentmethod) {
        this.assessmentmethod = assessmentmethod == null ? null : assessmentmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades.remarks
     *
     * @return the value of grades.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades.remarks
     *
     * @param remarks the value for grades.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }


}