package com.waxjx.largescale.model;

import java.util.Date;

public class Student {

    private String studentid;
    private String studentname;
    private String studenttelephone;
    private Short sex;
    private String college;
    private String administrativeclass;
    private String idnumber;
    private String email;
    private Short studentstatus;
    private Short educationalsystem;
    private Date enrollmentdate;
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentId
     *
     * @return the value of student.studentId
     *
     * @mbg.generated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentId
     *
     * @param studentid the value for student.studentId
     *
     * @mbg.generated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentName
     *
     * @return the value of student.studentName
     *
     * @mbg.generated
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentName
     *
     * @param studentname the value for student.studentName
     *
     * @mbg.generated
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentTelephone
     *
     * @return the value of student.studentTelephone
     *
     * @mbg.generated
     */
    public String getStudenttelephone() {
        return studenttelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentTelephone
     *
     * @param studenttelephone the value for student.studentTelephone
     *
     * @mbg.generated
     */
    public void setStudenttelephone(String studenttelephone) {
        this.studenttelephone = studenttelephone == null ? null : studenttelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.college
     *
     * @return the value of student.college
     *
     * @mbg.generated
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.college
     *
     * @param college the value for student.college
     *
     * @mbg.generated
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.administrativeClass
     *
     * @return the value of student.administrativeClass
     *
     * @mbg.generated
     */
    public String getAdministrativeclass() {
        return administrativeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.administrativeClass
     *
     * @param administrativeclass the value for student.administrativeClass
     *
     * @mbg.generated
     */
    public void setAdministrativeclass(String administrativeclass) {
        this.administrativeclass = administrativeclass == null ? null : administrativeclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.idNumber
     *
     * @return the value of student.idNumber
     *
     * @mbg.generated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.idNumber
     *
     * @param idnumber the value for student.idNumber
     *
     * @mbg.generated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentStatus
     *
     * @return the value of student.studentStatus
     *
     * @mbg.generated
     */
    public Short getStudentstatus() {
        return studentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentStatus
     *
     * @param studentstatus the value for student.studentStatus
     *
     * @mbg.generated
     */
    public void setStudentstatus(Short studentstatus) {
        this.studentstatus = studentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.educationalSystem
     *
     * @return the value of student.educationalSystem
     *
     * @mbg.generated
     */
    public Short getEducationalsystem() {
        return educationalsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.educationalSystem
     *
     * @param educationalsystem the value for student.educationalSystem
     *
     * @mbg.generated
     */
    public void setEducationalsystem(Short educationalsystem) {
        this.educationalsystem = educationalsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.enrollmentDate
     *
     * @return the value of student.enrollmentDate
     *
     * @mbg.generated
     */
    public Date getEnrollmentdate() {
        return enrollmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.enrollmentDate
     *
     * @param enrollmentdate the value for student.enrollmentDate
     *
     * @mbg.generated
     */
    public void setEnrollmentdate(Date enrollmentdate) {
        this.enrollmentdate = enrollmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.major
     *
     * @return the value of student.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.major
     *
     * @param major the value for student.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }
}