package com.waxjx.largescale.model;

import java.util.Date;

public class Teachers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.teacherID
     *
     * @mbg.generated
     */
    private String teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.sex
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.birthDate
     *
     * @mbg.generated
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.teacherID
     *
     * @return the value of teachers.teacherID
     *
     * @mbg.generated
     */
    public String getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.teacherID
     *
     * @param teacherid the value for teachers.teacherID
     *
     * @mbg.generated
     */
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid == null ? null : teacherid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.name
     *
     * @return the value of teachers.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.name
     *
     * @param name the value for teachers.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.sex
     *
     * @return the value of teachers.sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.sex
     *
     * @param sex the value for teachers.sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.birthDate
     *
     * @return the value of teachers.birthDate
     *
     * @mbg.generated
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.birthDate
     *
     * @param birthdate the value for teachers.birthDate
     *
     * @mbg.generated
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.title
     *
     * @return the value of teachers.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.title
     *
     * @param title the value for teachers.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.telephone
     *
     * @return the value of teachers.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.telephone
     *
     * @param telephone the value for teachers.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.remarks
     *
     * @return the value of teachers.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.remarks
     *
     * @param remarks the value for teachers.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}